"""
航空公司。
"""

AIRLINE = {
    "CA": "国航",
    "CZ": "南航",
    "MU": "东航",
    "PN": "西部",
    "MF": "厦航",
    "SC": "山东",
    "EU": "成都",
    "FM": "上航",
    "ZH": "深圳",
    "X2": "新华",
    "JR": "幸福",
    "3Q": "云南",
    "XQ": "新疆",
    "3U": "四川",
    "Z2": "中原",
    "WU": "武汉",
    "G4": "贵州",
    "HU": "海南",
    "GP": "通航",
    "3W": "南京",
    "ZJ": "浙江",
    "G8": "长城",
    "FJ": "福建",
    "9H": "长安",
    "GJ": "长龙",
    "JD": "首都",
    "HO": "吉祥",
    "9C": "春秋",
    "GS": "天津",
    "G5": "华夏",
    "KA": "Cathay",
    "KE": "Korean Air",
    "OZ": "Asiana",
    "JL": "Japan Air",
    "NH": "All Nippon",
    "SQ": "Singapore",
    "TG": "Thai",
    "NW": "Northwest",
    "AC": "Air Canada",
    "UA": "United",
    "BA": "British",
    "KL": "Clipper",
    "LH": "Lufthansa",
    "AF": "Air France",
    "LX": "Swiss",
    "OS": "Qantas",
    "SU": "Aeroflot",
    "QF": "Qantas",
    "AY": "Finnair",
    "AZ": "Alitalia",
    "SK": "Scandinavian",
    "BI": "Brunei",
    "GA": "Garuda",
    "JS": "Air Koryo",
    "CX": "Cathay Pacific",
    "NX": "Air Macau",
    "IR": "Iran Air",
}
"""
航空公司从二字代码到呼号的映射。
"""
